config/routes.rb
Rails.application.routes.draw do

  root 'blogs#index' #トップページをblogsコントローラのindexアクションに設定

  get 'blogs/index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'

  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'

  resources :answers
  resources :questions
  resources :mycontacts
  get 'messages/index'
  get 'messages', to: 'messages#index'

  get 'messages/add'
  post 'messages/add', to: 'messages#create'

  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'

  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'

  get 'cards/index'
  get 'cards', to: 'cards#index'
  get 'cards/add'
  post 'cards/add'
  get 'cards/:id', to: 'cards#show'
  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'

  get 'cards/delete/:id', to: 'cards#delete'
  get 'people/index'
  get 'people', to: 'people#index'
  get 'people/find'
  post 'people/find'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people/:id', to: 'people#show'
  get 'people/edit/:id', to: 'people#edit'
  post 'people/edit/:id', to: 'people#update'
  patch 'people/edit/:id', to: 'people#update'
  get 'people/delete/:id', to: 'people#delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index'
  get 'hello', to: 'hello#index'
  get 'hello/other'
  post 'hello', to: 'hello#index'
  post 'hello/index'
  get 'msgboard', to: 'msgboard#index'
  post 'msgboard', to: 'msgboard#index'
  get 'msgboard/index'
  post 'msgboard/index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :content, :name, presence: {message:'は、必須項目です。'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
  validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
  has_many :blogpost

  validates :name, presence: {message:'は、必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  belongs_to :bloggenre
  has_rich_text :content

  validates :title, :content, presence: {message:'は、必須項目です。'}
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :person
  validates :message, presence: {message:'を書いてください。'}
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
  validates :name, presence: {message:'は、必須項目です。'}
  validates :age, numericality: {message:'は、数字で入力してください。'}
  validates :nationality, inclusion: {in: [true, false], message:'は、真偽値です。'}
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :message

  validates :name, presence: { message: 'は、必須項目です。' }
  validates :age, numericality: { message: 'は、数字で入力してください。' }
  validates :mail, email: { message: 'はメールアドレスではありません' }
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answer

  validates :content, :name, presence: {message:'は、必須項目です。'}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  layout 'Q&A'

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order created_at: :desc
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
    @answer.question_id = params[:id]
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    redirect_to '/questions'
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/questions' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    redirect_to '/questions'
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    redirect_to '/questions'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :content, :name, :finished)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggenres_helper.rb
module BloggenresHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/msgboard_helper.rb
module MsgboardHelper
end

app/helpers/mycontacts_helper.rb
module MycontactsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% if question.errors.any? %>
  <div id="error_explanetion">
    <h2><%= pluralize(question.errors.count, "error") %>
      prohibited this question from being saved:</h2>
    <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(question) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, rows:5, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <%= f.hidden_field :finished, { value:false } %>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_form2.html.erb
<% if answer.errors.any? %>
  <div id="error_explanetion">
    <h2><%= pluralize(answer.errors.count, "error") %>
      prohibited this answer from being saved:</h2>
    <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(answer) do |f| %>
  <%= f.hidden_field :question_id, {value: answer.question_id} %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, row:2, class:"form-control" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Questions</h1>

<table class="table mt-5 mb-5">
  <thead>
    <tr>
      <th>Title</th>
      <th>Finished</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.finished ? '終了' : '受付中' %></td>
        <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '※新たに質問する', new_question_path %>

app/views/questions/new.html.erb
<h1 class="display-4 text-primary">New Question</h1>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Question & Answers</h1>

<div class="jumbotron p-4 mb-4">
  <h2 class="card-title">
    <%= @question.title %>
  </h2>
  <p class="card-text">
    <%= @question.content %>
  </p>
  <p class="blockquote-footer text-right">
    <%= @question.name %>
  </p>
  <div class="<%= @question.finished ? 'text-danger' : 'text-primary' %>">
    <%= @question.finished ? '終了' : '受付中' %>
  </div>
</div>

<% if @question.finished? == false then %>
  <div class="card p-3 mb-4">
    <h3 class="h4 text-primary">※回答する</h3>
    <%= render 'form2', answer: @answer %>
  </div>
<% end %>

<h3 class="h4 text-primary">※これまで寄せられた回答</h3>

<ul class="list-group">
<% if @question.answer.count == 0 then %>
  <p class="answer">※まだありません。</p>
<% else %>
  <% @question.answer.reverse_each do |re| %>
    <li class="list-group-item">
      <%= re.content + '（' + re.name + '）' %>
    </li>
  <% end %>
<% end %>
</ul>